export const DegustationItemsSizeS = [
  {
    id: "ds1",
    img: "/images/pies/pie2.png",
    isDegustationBox: true,
    name: "Шоколадный чизкейк",
    weight: "100 гр",
    leaf: "117 кКал",
  },
  {
    id: "ds2",
    img: "/images/pies/pie3.png",
    isDegustationBox: true,
    name: 'Чизкейк "Клубничный"',
    weight: "100 гр",
    leaf: "120 кКал",
  },
  {
    id: "ds3",
    img: "/images/pies/pie4.png",
    isDegustationBox: true,
    name: 'Торт "Чёрное и белое"',
    weight: "140 гр",
    leaf: "95 кКал",
  },
  {
    id: "ds4",
    img: "/images/pies/pie6.png",
    isDegustationBox: true,
    name: 'Торт "Пряная вишня"',
    weight: "100 гр",
    leaf: "125 кКал",
  },
];

export const DegustationItemsSizeM = [
  {
    id: "dm1",
    img: "/images/pies/pie2.png",
    isDegustationBox: true,
    name: "Шоколадный чизкейк",
    weight: "100 гр",
    leaf: "117 кКал",
  },
  {
    id: "dm2",
    img: "/images/pies/pie3.png",
    isDegustationBox: true,
    name: 'Чизкейк "Клубничный"',
    weight: "100 гр",
    leaf: "120 кКал",
  },
  {
    id: "dm3",
    img: "/images/pies/pie4.png",
    isDegustationBox: true,
    name: 'Торт "Чёрное и белое"',
    weight: "140 гр",
    leaf: "95 кКал",
  },
  {
    id: "dm4",
    img: "/images/pies/pie6.png",
    isDegustationBox: true,
    name: 'Торт "Пряная вишня"',
    weight: "100 гр",
    leaf: "125 кКал",
  },
  {
    id: "dm5",
    img: "/images/cupcakes/cupcake1.png",
    isDegustationBox: true,
    name: "Капкейк Шоколадный",
    weight: "100 гр",
    leaf: "422 кКал",
  },
  {
    id: "dm6",
    img: "/images/cupcakes/cupcake2.png",
    isDegustationBox: true,
    name: "Капкейк Карамельный",
    weight: "100 гр",
    leaf: "435 кКал",
  },
  {
    id: "dm7",
    img: "/images/cupcakes/cupcake4.png",
    isDegustationBox: true,
    name: "Капкейк Миндальный",
    weight: "100 гр",
    leaf: "456 кКал",
  },
  {
    id: "dm8",
    img: "/images/cupcakes/cupcake5.png",
    isDegustationBox: true,
    name: "Капкейк Красный бархат",
    weight: "100 гр",
    leaf: "415 кКал",
  },
];

export const DegustationItemsSizeL = [
  {
    id: "dl1",
    img: "/images/pies/pie2.png",
    isDegustationBox: true,
    name: "Шоколадный чизкейк",
    weight: "100 гр",
    leaf: "117 кКал",
  },
  {
    id: "dl2",
    img: "/images/pies/pie3.png",
    isDegustationBox: true,
    name: 'Чизкейк "Клубничный"',
    weight: "100 гр",
    leaf: "120 кКал",
  },
  {
    id: "dl3",
    img: "/images/pies/pie4.png",
    isDegustationBox: true,
    name: 'Торт "Чёрное и белое"',
    weight: "140 гр",
    leaf: "95 кКал",
  },
  {
    id: "dl4",
    img: "/images/pies/pie6.png",
    isDegustationBox: true,
    name: 'Торт "Пряная вишня"',
    weight: "100 гр",
    leaf: "125 кКал",
  },
  {
    id: "dl5",
    img: "/images/cupcakes/cupcake1.png",
    isDegustationBox: true,
    name: "Капкейк Шоколадный",
    weight: "100 гр",
    leaf: "422 кКал",
  },
  {
    id: "dl6",
    img: "/images/cupcakes/cupcake2.png",
    isDegustationBox: true,
    name: "Капкейк Карамельный",
    weight: "100 гр",
    leaf: "435 кКал",
  },
  {
    id: "dl7",
    img: "/images/cupcakes/cupcake4.png",
    isDegustationBox: true,
    name: "Капкейк Миндальный",
    weight: "100 гр",
    leaf: "456 кКал",
  },
  {
    id: "dl8",
    img: "/images/cupcakes/cupcake5.png",
    isDegustationBox: true,
    name: "Капкейк Красный бархат",
    weight: "100 гр",
    leaf: "415 кКал",
  },
  {
    id: "dl9",
    img: "/images/cakes/cake1.png",
    isDegustationBox: true,
    name: "Пирожное Фисташка-ваниль-малина",
    weight: "100 гр",
    leaf: "323 кКал",
  },
  {
    id: "dl10",
    img: "/images/cakes/cake2.png",
    isDegustationBox: true,
    name: "Пирожное Шоколадная страсть",
    weight: "100 гр",
    leaf: "335 кКал",
  },
  {
    id: "dl11",
    img: "/images/cakes/cake3.png",
    isDegustationBox: true,
    name: "Пирожное веганское",
    weight: "100 гр",
    leaf: "442 кКал",
  },
  {
    id: "dl12",
    img: "/images/cakes/cake5.png",
    isDegustationBox: true,
    name: "Пирожное А-ля Киевский",
    weight: "100 гр",
    leaf: "403 кКал",
  },
];
